
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "monitorDataWS", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonitorDataWS {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMonitorData", targetNamespace = "http://WebService/", className = "webservice.SetMonitorData")
    @ResponseWrapper(localName = "setMonitorDataResponse", targetNamespace = "http://WebService/", className = "webservice.SetMonitorDataResponse")
    @Action(input = "http://WebService/monitorDataWS/setMonitorDataRequest", output = "http://WebService/monitorDataWS/setMonitorDataResponse")
    public void setMonitorData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        MonitorData arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTerminalData", targetNamespace = "http://WebService/", className = "webservice.SetTerminalData")
    @ResponseWrapper(localName = "setTerminalDataResponse", targetNamespace = "http://WebService/", className = "webservice.SetTerminalDataResponse")
    @Action(input = "http://WebService/monitorDataWS/setTerminalDataRequest", output = "http://WebService/monitorDataWS/setTerminalDataResponse")
    public void setTerminalData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TerminalData arg1);

}
